# -*- coding: utf-8 -*-
"""DNN_CLASSIFICATIONTASK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rm5vX6zdTJBJOQXtMfwTvDssNuQd4Jno

**Aim:**
To implement a Deep Neural Network (DNN) for a classification task using TensorFlow and Keras.

**Algorithm**

1. Import the required libraries.

2. Load the dataset.

3. Split the dataset into training and testing sets.

4. Normalize the input features.

5. Build a Deep Neural Network with input, hidden, and output layers.

6. Compile the model using an optimizer and loss function.

7. Train the model.

8. Evaluate the model.

9. Predict the class labels for test data.

**ARCHITECTURE**

**Input Layer
(4 Features)**

      │
      ▼
**Hidden Layer 1
(16 Neurons)**

ReLU

      │
      ▼
**Hidden Layer 2
(8 Neurons)**

ReLU

      │
      ▼
**Output Layer
(3 Neurons)**

Softmax

      │
      ▼
Predicted Class
"""

# Step 1: Import libraries
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Step 2: Load dataset
iris = load_iris()
X = iris.data
y = iris.target

#see the sample size & no of features
print(X.shape)
print(y.shape)
print(iris.target_names)

# Step 3: Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42  #controls the randomness used while splitting the dataset.
)

# Step 4: Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Step 5: Create Deep Neural Network with DENSE model
model = Sequential() #Creates a sequential neural network where layers are added one after another.

# Input + Hidden Layer 1
model.add(Dense(16, activation='relu', input_shape=(4,)))

# Hidden Layer 2
model.add(Dense(8, activation='relu'))

# Output Layer
model.add(Dense(3, activation='softmax'))

# Step 6: Compile model
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Step 7: Train model
model.fit(X_train, y_train, epochs=50, batch_size=8)

# Step 8: Evaluate model
loss, accuracy = model.evaluate(X_test, y_test)

print("Test Accuracy:", accuracy)

# Step 9: Prediction
predictions = model.predict(X_test)

predicted_class = tf.argmax(predictions, axis=1)

print("Predicted Classes:")
print(predicted_class.numpy())

print("Actual Classes:")
print(y_test)