# -*- coding: utf-8 -*-
"""word2vec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ETH9wVB-TTJzmaVqyp3QKCR7G0HeLyq-

**EXPERIMENT:Design and Implement a Neural Network for Generating Word Embeddings**





***AIM:*** **To design and implement a neural network for generating word embeddings from a :document corpus using the Word2Vec model.**

Word embeddings are dense vector representations
of words where semantically similar words are located close together in the vector space.

Unlike One-Hot Encoding, which creates sparse vectors, Word2Vec learns meaningful numerical representations by training a shallow neural network.

**Two architectures are commonly used:**

1)Continuous Bag of Words (CBOW)
Predicts the target word from surrounding context words.
Faster to train.
Performs well on smaller datasets.

2)Skip-Gram
Predicts surrounding words from the target word.
Better captures rare words.
Performs well on larger datasets.

**ALGORITHM**

1 Load the document corpus.

2 Perform text preprocessing.

3 Convert to lowercase.

4 Remove punctuation.

5 Tokenize sentences.

6 Train a Word2Vec model.

7 Learn dense vector representations.

8 Retrieve embedding vectors.

9 Compute similarity between words.

10 Display nearest similar words.
"""

import nltk
 !pip install gensim nltk
 nltk.download('punkt_tab')

# Install once if required
import nltk
from nltk.tokenize import word_tokenize
from gensim.models import Word2Vec

nltk.download('punkt')

# Sample document corpus
documents = [
    "Deep learning is a subset of machine learning",
    "Machine learning enables computers to learn",
    "Neural networks are the foundation of deep learning",
    "Artificial intelligence includes machine learning and deep learning",
    "Word embeddings capture semantic relationships between words"
]

# Preprocessing
processed_docs = []

for doc in documents:
  tokens = word_tokenize(doc.lower())
  processed_docs.append(tokens)

print("Tokenized Corpus:\n")
print(processed_docs)

# Train Word2Vec Model
model = Word2Vec(
    sentences=processed_docs,
    vector_size=100,
    window=2,
    min_count=1,
    workers=4
)

# Save model (optional)
model.save("word2vec.model")

# Display Vocabulary
print("\nVocabulary:")
print(model.wv.index_to_key)

# Word Vector
word = "learning"

print(f"\nEmbedding Vector for '{word}':\n")
print(model.wv[word])

# Similar Words
print("\nMost Similar Words:")
print(model.wv.most_similar("learning"))

"""**Parameter	               Description**

vector_size=100	    Size of the embedding vector

window=2	          Number of neighboring words considered

min_count=1	        Includes every word appearing at least once

workers=4	Number of CPU cores used for training
"""